version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily
    labels:
      - dependencies
      - frontend
    open-pull-requests-limit: 5
    groups:
      frontend-minor-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: daily
    labels:
      - dependencies
      - backend
    open-pull-requests-limit: 5
    groups:
      backend-minor-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: daily
    labels:
      - dependencies
      - docker
      - backend
    groups:
      backend-docker:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: daily
    labels:
      - dependencies
      - docker
      - frontend
    groups:
      frontend-docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"
