server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  gzip on;
  gzip_http_version 1.0;
  gzip_proxied any;
  gzip_vary on;
  gzip_comp_level 5;
  gzip_min_length 1024;
  gzip_types text/css text/javascript application/javascript application/json image/svg+xml text/plain application/manifest+json;

  location /assets/ {
    add_header Cache-Control "max-age=31536000, immutable";
  }

  location = /index.html {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
  }

  location / {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    try_files $uri $uri/ /index.html;
  }
}
